# Generated by Django 4.2 on 2025-11-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('num_questions_in_round', models.IntegerField(default=0)),
                ('cost_per_round', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('times_played', models.IntegerField(default=1)),
                ('rounds_data', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('rewards', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_questions', to='game.game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_in_games', to='application.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='questions',
            field=models.ManyToManyField(related_name='games', through='game.GameQuestion', to='application.question'),
        ),
    ]
